apiVersion: v1
kind: ServiceAccount
metadata:
  name: bad_pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad_pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bad_pod
  template:
    metadata:
      labels:
        app: bad_pod
    spec:
      serviceAccountName: bad_pod
      shareProcessNamespace: true
      securityContext:
        runAsUser: 999
        fsGroup: 999
      containers:
      - name: bad_pod
        image: portainer/kubectl-shell:latest-v1.21.1-amd64
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /etc/bad_pod/tls
          name: secret-volume
          mountPropagation: 
      volumes:
      - name: secret-volume
        secret:
          secretName: bad_pod-secret
          optional: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: allow_pod_read
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow_pod_read_bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: allow_pod_read
subjects:
- kind: ServiceAccount
  name: bad_pod

